module.exports = (grunt) ->

  grunt.initConfig
    pkg: grunt.file.readJSON("package.json")
    comments: """
// Chosen, a Select Box Enhancer for jQuery and Protoype
// by Patrick Filler for Harvest, http://getharvest.com
//
// Version <%= pkg.version %>
// Full source at https://github.com/harvesthq/chosen
// Copyright (c) 2011 Harvest http://getharvest.com

// MIT License, https://github.com/harvesthq/chosen/blob/master/LICENSE.md
// This file is generated by `cake build`, do not edit it by hand.\n
"""

    concat:
      options:
        banner: "<%= comments %>"
      jquery:
        src: ["chosen/chosen.jquery.js"]
        dest: "chosen/chosen.jquery.js"
      proto:
        src: ["chosen/chosen.proto.js"]
        dest: "chosen/chosen.proto.js"

    coffee:
      compile:
        files:
          'chosen/chosen.jquery.js': ['coffee/lib/select-parser.coffee', 'coffee/lib/abstract-chosen.coffee', 'coffee/chosen.jquery.coffee']
          'chosen/chosen.proto.js': ['coffee/lib/select-parser.coffee', 'coffee/lib/abstract-chosen.coffee', 'coffee/chosen.proto.coffee']

    uglify:
      options:
        mangle:
          except: ['jQuery']
        banner: "<%= comments %>"
      my_target:
        files:
          'chosen/chosen.jquery.min.js': ['chosen/chosen.jquery.js']
          'chosen/chosen.proto.min.js': ['chosen/chosen.proto.js']

    watch:
      scripts:
        files: ['coffee/**/*.coffee']
        tasks: ['build']

  grunt.loadNpmTasks 'grunt-contrib-coffee'
  grunt.loadNpmTasks 'grunt-contrib-uglify'
  grunt.loadNpmTasks 'grunt-contrib-concat'
  grunt.loadNpmTasks 'grunt-contrib-watch'

  grunt.registerTask 'build', ['coffee', 'concat', 'uglify']

